fool = {
	       0: ["Słowa kluczowe – początek, nowa faza życia, ciekawe perspektywy, entuzjazm, instynkt, fascynacja, wiara, odejście od przeszłości, nieprzewidziane wydarzenie, przypadek, wolność.",
	           "Osoba – Dziecko,  ktoś młody, osoba dorosła ale młoda duchem, niezrozumiany geniusz, pielgrzym, satyryk, podróżnik, emigrant, pracownik sezonowy, awanturnik, wariat. Karta może symbolizować  również zwierzęta.",
	           "Miejsce – Żłobek, przedszkole, szkoła podstawowa, pokój dziecinny, spontaniczna impreza w plenerze, grill lub piknik, podróż autostopem, pobyt w nowym miejscu, szlak turystyczny, trasa pielgrzymki, miejsce trudne do określenia."], 
	       1: ["Cechy ogólne – Spontaniczność, niekonwencjonalność, entuzjazm, ufność, niewinność, nadzieja, beztroska, optymizm, poczucie humoru, otwartość na świat, wszelkie nowinki i eksperymenty, ogólnie człowiek żywiołowy z fantazją.",
	           "Ogólne znaczenie – Karta jest symbolem czegoś nowego w naszym życiu lub sytuacji, kiedy znajdujemy się na rozdrożu po tzw. przejściach. Trzeba będzie uporać się z wątpliwościami i obawami, zakończyć stary etap i z nadzieją pójść do przodu. Warunkiem powodzenia będzie wiara, pewność siebie, entuzjazm i chęć poniesienia ryzyka. To co skostniałe lub bolesne musi odejść czy chcemy czy nie. Na planie życia może to być np. początkowa faza związku, szalone zakochanie, zmiana miejsca zamieszkania, rozpoczęcie nauki, pracy, nowy pomysł w sferze zawodowej, dobra zabawa, podróż, zauroczenie, znalezienie nowej pasji, spotkanie człowieka pełnego zwariowanych pomysłów, szalonego, pełnego wigoru i tryskającego energią (również seksualną). Karta może oznaczać także chęć inicjacji seksualnej albo tak przykre zdarzenie jak  przypadkowe zajście w ciążę. Głupiec uśmiecha się do nas i mówi ,  koniec ze smutkiem, nie żyjemy tu przecież za karę, głowa do góry, korzystajmy i doceniajmy wartość cudu życia"],
	       2: ["Karta odwrócona– Niedojrzała osobowość, która uczy się na własnych błędach, tzw. dziecko z problemami, ekscentryzm, upór, niezależność za wszelką cenę, bezmyślność, dziwaczność, niesłowność, niepunktualność, nieobliczalność w zachowaniu, infantylizm, skrajna naiwność granicząca z głupotą, podejmowanie pochopnych decyzji, postawa życiowa kiedy żyje się z dnia na dzień bez chęci ustatkowania się.",
	           "Karta odwrócona ostrzega przed kłamliwymi, nieodpowiedzialnymi ludźmi i nieuczciwymi sytuacjami, zbytnim nieuzasadnionym ryzykiem, zachowaniami które nie przynoszą niczego dobrego ani nam ani innym. Zwraca uwagę na brak analizy, chaos, brak orientacji, bezmyślność, dziwactwa. Oznacza też żebractwo i ucieczkę oraz biseksualność.",
	           "Zdrowie (karta odwrócona)- Choroby zakaźne wieku dziecięcego, które mogą również dotyczyć dorosłych, choroby wrodzone układu krążenia, pokarmowego lub hormonalnego, cukrzyca typu I, wrodzone upośledzenie umysłowe."],}

wizard = {
	       0: ["Słowa kluczowe – energiczne działanie, intuicja, wielki  wpływ na innych, sukces, charyzma, potencjał, profesjonalizm, wiedza, branie spraw w swoje ręce, mistrzostwo w jakiejś dziedzinie, wywieranie wrażenia",
	           "Osoba– Młody mężczyzna, uczeń, mag, kuglarz, bioenergoterapeuta, informatyk, dziennikarz, dyplomata, artysta, osoba wpływowa, kłamca,plotkarz.",
	           "Miejsce- Gimnazjum, szkoła średnia, instytut naukowy, biblioteka, gabinet naukowy, biuro, giełda, teatr, poczta, dom handlowy.",], 
	       1: ["Cechy ogólne – Pewność siebie, siła osobowości i wyobraźni, talent, duża wiedza, mądrość, aktywność, radzenie sobie z każdym wyzwaniem, przebiegłość, zręczność, zdrowy rozsadek, dar przekonywania do swoich racji- siła sugestii, dar zjednywania sobie ludzi i pięknego wysławiania, dobra koncentracja, mistrzostwo w dziedzinie nowoczesnej techniki.",
	           "Ogólne znaczenie– Mag to archetyp człowieka sukcesu.  Kiedy więc pojawi się w rozkładzie może oznaczać, że osoba której wróżymy ma wszystkie cechy potrzebne do osiągnięcia dowolnego celu. Musi tylko wziąć sprawy w swoje ręce zdobywając potrzebna wiedzę i wykazać się twórczym działaniem. Ważne aby wszelkie decyzje dotyczące własnego życia podejmowała samodzielnie.  Może oznaczać, że sytuacja wymaga zdecydowania i zręczności lub pomocy innej osobie. Może znaczyć także że w życiu osoby której wróżymy pojawi się taka wspaniała postać. Mądra i wpływowa, z której rad lub pomocy dobrze skorzystać. W pytaniach o pracę oznacza,  sukcesy i talent do rozwiązań tam, gdzie inni ponoszą porażki. Ogólnie, należy wykazać się komunikatywnością, być przygotowanym na różne opcje, zmienne sytuacje, trzeba być elastycznym i twórczym, wykorzystywać nadarzające się sytuacje, nie czekać a odważnie i mądrze działać. W pytaniach o miłość  będzie symbolem tej cudownej właściwej osoby. Dla kobiet może oznaczać wspaniałego, upragnionego mężczyznę i szalone przeżycia erotyczne."],
	       2: ["Karta odwrócona – Nadużywanie władzy, manipulacje, plotkarstwo, gadatliwość, kłótliwość, problemy w komunikacji z innymi, kłamstwa, oszustwa, problemy z koncentracją, i wymową, nieumiejętność konkretnego działania, marnowanie dobrych okazji,  niedojrzałość, przecenianie swoich możliwości, wykorzystywanie wiedzy do złych celów.",
	           "Karta odwrócona  – Oznacza ostrzeżenie przed manipulacją z zewnątrz lub przed niebezpieczeństwem. Z jednej strony karta ostrzega przed zbytnią pewnością siebie i skupianiem się wyłącznie na sobie z drugiej zaś strony może   sygnalizować problem z zaakceptowaniem siebie, brakiem pewności, z trudnością komunikowania się z innymi. Tak czasem bywa że za zbytnią pewnością siebie chowamy głęboko skrywane kompleksy.",
	           "Zdrowie (karta odwrócona) – Problemy z górnymi drogami oddechowymi; jama ustną, gardłem, krtanią, migdałkami np. angina, grypa, zapalenie krtani, przeziębienia. Wszelkie problemy związane ze słuchem i mową. Głuchota, infekcje ucha, jąkanie, wszelkie wady wymowy. Karta może oznaczać wszelkie alergie wziewne."],}

priestess = {
	       0: ["Słowa kluczowe – mądrość, wiedza, osobowość, intuicja, instynkt, tajemnica, ukryte działania, skrywane emocje, ambicja, żeńska siła duchowa, rozwój talentów, pamięć o ważnych sprawach, milcząca potęga, wpływ na bieg spraw, odkrywanie tajemnic.",
	           "Osoba– Dojrzała kobieta, łagodna matka posiadająca dorosłe dzieci, opiekunka, mądra przyjaciółka, wróżka lub wróżbita, tarocistka, psycholog, zakonnik, pisarz, poeta, nauczyciel, strażnik,toksyczna matka, kochanka, szpieg,tajne stowarzyszenia, sekty. Karta może oznaczać osobę małomówną.",
	           "Miejsce– Kościół, konfesjonał, uczelnia, biblioteka, księgarnia, sejf, miejsce do nauki i medytacji, dziewiczy teren nie tknięty cywilizacją,",], 
	       1: ["Cechy ogólne– Intuicja, wrażliwość, empatia, opieka, dobroć, dyskrecja, subtelność, uczciwość, ciepło, cierpliwość, wytrwałość, łagodność, miłosierdzie, ambicja, zdolność do przeżywania miłości uniwersalnej, uczuciowość, umiejętność przekazywania wiedzy duchowej, powiernictwo,  dobroczynny wpływ na innych.",
	           "Znaczenie ogólne – Karta Kapłanki jako archetyp wszystkiego co nieznane, mówi aby w danej sytuacji zawierzyć własnej intuicji, wsłuchać się we własny wewnętrzny głos. Zaleca nie spieszyć się z działaniem, poczekać na impuls z zewnątrz, zachować równowagę emocjonalną, ponieważ i tak doznamy „oświecenia” po wnikliwym zanalizowaniu sytuacji lub ostrzega że  zetknęliśmy się z sytuacją, w której coś jest ukrywane. Karta oznacza również wewnętrzną potrzebę zgłębiania wiedzy ezoterycznej, rozwijanie talentów oraz wszelkich uzdolnień. Być może mamy wielki wpływ na ludzi, emanujemy ciepłem, dobrocią, potrafimy otaczać ludzi miłością i opieką. Jako wrażliwe i mądre istoty niesiemy innym radość i wsparcie. Intuicyjnie wyczuwamy ludzkie potrzeby i problemy. W takim wypadku karta namawia do rozwijania w sobie tych cech i pozostanie osobą skromną, doceniającą każdą chwilę życia. Może też symbolizować mądrą i intuicyjną kobietę, która będzie mieć duży wpływ na bieg zdarzeń, które są dla nas ważne. W sprawach uczuć może oznaczać skrywaną w sercu miłość lub sytuację, która wymaga większego zrozumienia. Ze względu na trudną sytuację należałoby podjąć poważną rozmowę z partnerem albo zweryfikować toksyczne związki. W każdym razie nie można traktować problemu zbyt powierzchownie. Karta symbolizuje wyższe uczucia, niezwykłe porozumienie między dwojgiem ludzi, związek z przeznaczenia, może oznaczać tzw. białe małżeństwo.",
	           "Karta Kapłanki może symbolizować także różnego rodzaju dokumenty, które już istnieją lub takie, które trzeba zredagować. Kolejne znaczenie karty to ostrzeżenie przed podjęciem się wyjaśnienia jakiejś sprawy ze względu na brak konkretnej wiedzy. Istnieje więc konieczność zgłębienia jakiejś dziedziny wiedzy, przeczytanie jakiejś książki , zapisanie się na kursy, czy prozaicznie przeczytanie instrukcji obsługi."],
	       2: ["Karta odwrócona– Toksyczna osobowość, brak wiary we własne możliwości, bierność, naiwność, marzycielstwo, zmienność nastrojów, depresja, niemożność zrozumienia innych, lęki, niepewność, egoizm, powierzchowność, nieuczciwość w postępowaniu, zaskakujące okoliczności na które nie ma się wpływu, kłopoty przez starsze kobiety,  podstępna kobieta stosująca czarną magię.",
	           "Karta odwrócona– Oznacza brak intuicji, brak inicjatywy, niepowodzenia, ukryte intencje, niestabilność uczuciowa, melancholia, kompleksy, pedanteria, toksyczny związek, brak poczucia bezpieczeństwa.",
	           "Zdrowie (karta odwrócona) – Kłopoty z układem rozrodczym; zapalenia jajników, nadżerki, upławy, zaburzenia cyklu, bolesne miesiączki, mięśniaki macicy i cysty jajników. U mężczyzn zapalenie jąder, cewki moczowej. Karta symbolizuje bezpłodność i zaburzenia płodności wrodzone, nabyte oraz występujące pod wpływem blokad psychicznych u obu płci."],}
	           
empress = {
	       0: ["Słowa kluczowe – kobiecość, styl, indywidualność, dyplomacja, pomyślność, przyjemności zmysłowe, osobisty sukces, płodność, narodziny, macierzyństwo, opiekuńczość, współczucie, siła witalna, poczucie dobrego życia.",
	           "Osoba – Atrakcyjna i elegancka kobieta, mama, kobieta rodząca, siostra, ukochana, żona lub oficjalna partnerka, dorosła córka, prawdziwa dama w towarzystwie, kobieta na stanowisku, kochanka, kobieta dominująca,destrukcyjna i wyrachowana. Karta może oznaczać również delikatnego i miłego mężczyznę.",
	           "Miejsce– Muzea, pałace, wytworne sale, ambasady, piękne domy, przedsiębiorstwa, modne restauracje, ekskluzywne sklepy, salony kosmetyczne, sypialnie małżeńskie.",], 
	       1: ["Cechy ogólne– Ambicja, kreatywność, samodzielność i niezależność, dobry gust, pewność siebie, produktywne działanie, ciepło, wyrozumiałość, odpowiedzialność, pomoc i opieka, życzliwość. Zaspakajanie własnych i cudzych potrzeb. Rozsądne dbanie o zdrowie i urodę. Osoba wpływowa, motywująca innych do działania, czarująca, niezwykle ujmująca, pełna fantazji i miłości, która ma mądre i dojrzałe podejście do związku i rodziny.",
	           "Znaczenie ogólne – Jako archetyp obfitości, płodności i kreatywności będzie prezentować te cechy we wszystkich aspektach życia. Cesarzowa to piękna, zadbana kobieta, młoda mama, ukochana kobieta, postać twórcza, opiekuńcza i mądra. Kiedy pojawi się w rozkładzie na jakikolwiek temat będzie symbolem powodzenia i przyjemności. W rozkładzie dla mężczyzny będzie symbolem idealnej kobiety, która jest w jego życiu. W rozkładzie dla kobiety będzie oznaczać, że osoba której wróżymy właściwie kreuje swoją kobiecość, jest pewna siebie, czerpie satysfakcję ze swojego wyglądu i seksualności. Inne aspekty znaczenia tej karty to konieczność zwrócenia uwagi na własne potrzeby emocjonalne i fizyczne (również seksualne). Cesarzowa może oznaczać, że trzeba będzie odegrać opiekuńczą rolę wobec kogoś, poświęcając mu wiele czasu i uwagi. Piękny i romantyczny aspekt Cesarzowej to miłość i romans prowadzący do udanego małżeństwa i dzieci. Może także oznaczać kobietę oczekującą potomka w najbliższym otoczeniu. Reasumując karta Cesarzowej to wszelkie powodzenie, wdrażanie nowych planów, miłość, zmysłowość, macierzyństwo, opiekuńczość, obfitość, komfort, sukces materialny, stabilizacja w rodzinie, twórcza faza w życiu, zainteresowania sztuką (muzyka, poezja, malarstwo)."],
	       2: ["Karta odwrócona– Niedoskonałość, wszelkiego rodzaju niepowodzenia, brak gustu, chorowitość, zbytnia uległość lub zaborczość i dominacja, przesadne wymagania i chęć sprostania nierealnym kanonom urody, zbytni materializm, rozrzutność lub skąpstwo, złość, niewierność, niszcząca rywalizacja, mściwość i wyrachowanie.",
	           "Karta odwrócona– Oznacza wszelkiego rodzaju niepowodzenia, biedę, brak równowagi emocjonalnej, bezradność, powolne działanie, brak postępów w podjętych działaniach, umysłowe lenistwo, samotność, brak wsparcia i opieki, zazdrość,   fizyczne zaniedbanie, brak miłości macierzyńskiej, kłopoty z zajściem w ciążę lub ciąża niechciana, kłopoty z dziećmi, nieporozumienia i kłopoty w rodzinie. Problemy między małżonkami w wyniku zdrady, kłopoty w sferze intymnej oraz informacja że ktoś nalega na seks bez uczuć. Jeśli karta dotyczy mężczyzny oznacza że szuka nierealnego ideału kobiety, mając kłopoty z własną psychiką (zbytnia delikatność, nadwrażliwość).",
	           "Zdrowie (karta odwrócona) –Problemy związane z wyglądem zewnętrznym; zez, bielactwo, rozszczepienie wargi, łysienie plackowate, celulit. Blizny i oszpecenia, problemy skórne wymagające korekcji chirurgii plastycznej. Dolegliwości dermatologiczne: wszelkie wysypki,  egzemy,  pokrzywki, podrażnienia skóry."],}

emperor = {
	       0: ["Słowa kluczowe – autorytet, ojciec, władza, zasady, odpowiedzialność, odwaga, siła charakteru, dojrzałość, stabilność, dominacja.",
	           "Osoba- Dojrzały mężczyzna, ojciec, mąż, partner, osoba na eksponowanym stanowisku, urzędnik państwowy, osoba ciesząca się prestiżem i autorytetem, ktoś majętny, materialista, przedsiębiorca, lekarz, wojskowy, policjant. To także despota, tyran, kochanek, osoba dominująca. Karta może oznaczać również bardzo silną kobietę.",
	           "Miejsce – Stolica państwa, urząd, ratusz, zamek, pałac, kompleks zabytkowy, posiadłość ziemska, przedsiębiorstwo,  komisariat policji, koszary.",], 
	       1: ["Cechy ogólne –Realizm, rozsądek, porządek, przestrzeganie zasad, władza, mądrość, męstwo, szlachetność,  ambicje, obiektywizm, odpowiedzialność, obiektywna, sprawiedliwa ocena, inicjatywa, przestrzeganie ustalonych praw i porządku, wytrwałość w dążeniu do celu, samokontrola, szacunek, panowanie nad emocjami, stanowczość, myślenie dalekosiężne, dyplomacja,  wierność.",
	           "Znaczenie ogólne – Karta Cesarza to archetyp przywództwa, ojcostwa i władzy. Oznacza przejęcie odpowiedzialności, bycie dorosłym, dojrzałym człowiekiem oraz realizację jakiegoś przedsięwzięcia w dążeniu do dobrobytu. Może to też być jakaś ważna i życzliwa postać w naszym życiu lub to my stajemy się autorytetem i wsparciem dla kogoś. Kiedy pojawi się w rozkładzie może oznaczać że wkraczamy w etap kiedy wiemy czego chcemy, mamy konkretny plan i go realizujemy. Albo namawia nas aby tak wreszcie zrobić!!! Ruszyć do przodu. Uporządkować swoje życie czy to w aspekcie materialnym czy stosunków personalnych. Należy jednak zwrócić baczniejszą uwagę aby w tych poczynaniach uwzględnić innych, nie iść przez życie po trupach i nie realizować  czegoś za wszelką cenę. Trochę elastyczności jeszcze nikomu nie zaszkodziło. W pytaniach o  pracę karta informuje że  trzeba będzie wziąć sprawy w swoje ręce. Solidne przygotowanie i determinacja zagwarantują nam sukces. W kwestiach uczuć i związków karta oznacza fascynację kimś  dominującym, silnym, błyskotliwym osobowością spełnioną , człowiekiem sukcesu. Niekiedy karta ostrzega przed kimś kto nigdy nie odkryje swoich emocji i uczuć, pozostając  wyłącznie zimnym kochankiem. W związkach symbolizuje po prostu wiernego i odpowiedzialnego  małżonka, odpowiedzialnego ojca."],
	       2: ["Karta odwrócona –Despotyzm, tyrania, arogancja, nietolerancja, przekonanie o własnej nieomylności,  dominacja, brak taktu, nieodpowiedzialność, niedojrzałość, nadużywanie władzy, tchórzostwo, małostkowość, pedanteria, bezsilność, nieumiejętność podejmowania decyzji, dogmatyzm, chciwość, manipulacja, korupcja, lenistwo, problem z tzw. męskością negowanie jej albo typ „macho”.",
	           "Karta odwrócona – Problemy z kimś ważnym ojcem lub przełożonym, problemy rodzinne, kłopoty w związku z powodu zdrady (kochanek),brak kontroli nad uczuciami, przeciążenie obowiązkami, wyczerpanie, nieciekawa praca, zwolnienie z pracy, bezrobocie,  wygórowane ambicje nie adekwatne do możliwości.",
	           "Zdrowie (karta odwrócona) –Migrena, choroby zatok, choroby oczu, nosa, udary mózgu, wylewy, miażdżyca, urazy i skaleczenia głowy. Wszelkie dolegliwości związane z przepracowaniem, przemęczenie fizyczne i psychiczne."],}

pope = {
	       0: ["Słowa kluczowe – autorytet moralny, duchowość, mądrość, wiedza, doświadczenie, nauczyciel, zaufanie, refleksja, tradycyjne wartości, zasady i ceremonie, wierność ideałom, szacunek, poszukiwanie prawdy i sensu, powodzenie, dostatek.",
	           "Osoba – Ojciec, głowa rodu, duchowny, powiernik, psycholog, lekarz, profesor uniwersytetu, ksiądz z powołania, radca prawny, doradca, przyjaciel, intelektualista, dewotka, fałszywy prorok, kapłan bez powołania, destrukcyjny ojciec.",
	           "Miejsce – Miejsca kultu religijnego wszystkich wyznań, konfesjonał, uczelnie, instytuty naukowe, pomniki, domy opieki, gabinet radcy prawnego, gabinet psychoterapeutyczny, biuro matrymonialne.",], 
	       1: ["Cechy ogólne – Osoba o nieskazitelnej moralności, uosobienie dobra, wzór ojca, zrównoważony osąd, uczciwość, prawość, lojalność, życzliwość, szczodrość,  poświęcenie, akceptacja, szlachetność, mądrość, obiektywizm, rozsądek, pobożność, przywiązanie do tradycji, talent organizacyjny.",
	           "Znaczenie ogólne – Karta Kapłana to wymiernik wiedzy i nauki w szerokim znaczeniu. Może oznaczać osobę z autorytetem, kogoś na wysokim stanowisku, kto poprze nas w jakiejś sprawie. Albo otrzymamy jakąś nagrodę czy rekomendację do stopnia naukowego czy nominację na stanowisko naukowe lub związane z edukacją.  Inne znaczenie tej karty to  że być może znaleźliśmy się w sytuacji kiedy doświadczyliśmy głębszego zrozumienia siebie i swojego życia, jego roli i sensu. Próbujemy odnaleźć się w nowej sytuacji, rezygnując z dotychczasowych wzorców, przekonań i postępowania. Być może potrzebujemy duchowego wsparcia na tej drodze lub terapii u specjalisty. Może przeczytaliśmy książkę, która spowodowała zmianę priorytetów w naszym życiu. Co by to nie było ważne jest, że wkraczamy w nowy etap rozwoju, rozwijamy się duchowo i  możemy liczyć na pomoc ze strony autorytetu do którego  zwrócimy się o pomoc. Z drugiej strony być może posiadamy cechy o których mowa i możemy pomóc innym w dotarciu do poznania swojego głębszego ja. Karta Kapłana oznacza także że decyzja którą właśnie podejmujemy jest  słuszna albo ze musimy przystosować się do pewnych zasad, jeśli chcemy aby sprawa o którą pytamy posunęła się do przodu. Kiedy zobaczymy ją w rozkładzie będzie  oznaczać wszelkie umowy, kontrakty, ugody, rozejm i  legalizacje. Może symbolizować ceremonię ślubu kościelnego lub  chrzest."],
	       2: ["Karta odwrócona – Fałszywy autorytet, podwójna moralność, wykorzystanie czyjejś słabości, fanatyzm, hipokryzja, obłuda, nietolerancja, wrogość, fałszywa religijność, dewocja.",
	           "Karta odwrócona – Rozczarowanie  jakimś  autorytetem, problemy ze zdrowiem, złość, niechęć, bunt przeciwko utartym kanonom, regułom, zasadom moralnym. Toksyczny, destrukcyjny  ojciec, fałszywy prorok, kapłan bez powołania. Kłopoty  związane z brakiem ojca w dzieciństwie, nadmierna wpływowość, uleganie wpływom fałszywych autorytetów  (subkultur).",
	           "Zdrowie (karta odwrócona) – Choroby dziedziczne ; cukrzyca, choroby układu krążenia, otyłość, choroba wrzodowa żołądka i dwunastnicy, choroby nowotworowe. Problemy dermatologiczne; czyraczność, owrzodzenia, ropnie. Alergie skórne pod wpływem działania alergenów zewnętrznych np. kosmetyków, środków czystości, materiałów z dodatkiem chemii."],}

lovers = {
	       0: ["Słowa kluczowe – miłość, romans, bliskość, pokusa, związek,  małżeństwo, przyjaźń, droga wyboru, fascynacja, namiętność.",
	           "Osoba – Ukochana/y/, żona, mąż, przyjaciele, partnerzy, kochankowie, destrukcyjny partner lub partnerka,oszust matrymonialny.",
	           "Miejsce – Skrzyżowanie dróg, miejsce spotkań zakochanych, kawiarnie, kluby, sklepy, miejsca gdzie odbywa się handel, pierwsze mieszkanie lub dom.",], 
	       1: ["Cechy ogólne – Miłość, wrażliwość, fascynacja, zmysłowość, namiętność, oczarowanie, zauroczenie, pożądanie,  romantyzm, optymizm, pragnienia, marzenia.",
	           "Znaczenie ogólne – Karta dość skomplikowana mimo wyrazistej nazwy.  Jednak nie chodzi tu tylko o miłość, romans czy przyjemność. Ogólne znaczenie jest takie, że każdy z nas obojętnie jak bardzo jest zaangażowany w relacje z druga osobą, odczuwając bliskość emocjonalną czy fizyczną musi  wziąć pod uwagę dwoistość ludzkiej natury, ponieważ każdy człowiek to  odrębna istota. Może mieć inne pragnienia, potrzeby, uwarunkowania czy upodobania. Podejmując decyzję o byciu z kimś trzeba wziąć pod uwagę że będziemy musieli zaakceptować tę odrębność. Może być tak, że dla wspólnego dobra trzeba będzie pójść na kompromis albo zmienić coś w sobie. Musimy uświadomić sobie czym dla nas jest miłość i ile jesteśmy gotowi jej poświęcić? Czy jesteśmy gotowi na pewne ustępstwa czy pragniemy tylko brać, nie dając wiele w zamian. Czego tak naprawdę chcemy? Karta Kochanków oznacza nowy etap w życiu uczuciowym, wielkie zaangażowanie, nadzieję na udany związek, oczarowanie, jedność i oczekiwanie najlepszego. W rezultacie ten okres kończy się ślubem.  Może zdarzyć się też sytuacja wyboru pomiędzy dwiema osobami lub zaangażowanie się w romans z osobą będącą już w związku. Karta Kochanków oznacza podejmowanie decyzji o  przełomowym momencie w życiu i seksualnym zaangażowaniu się w danej relacji. Dla młodych osób może oznaczać podjęcie decyzji o rozpoczęciu współżycia, ten „pierwszy raz”. W codziennym życiu możemy stanąć przed wyborem zawodowym, czyli otrzymamy propozycje z dwóch miejsc. Albo w sytuacji rozwodu trzeba będzie podjąć decyzję z kim pozostaną dzieci. Kochankowie namawiają do miłości, udanych związków, do pielęgnowania istniejących relacji. Są kartą zaangażowania się z wielką pasją i miłością w nowe  pomysły  artystyczne  i wszystkie inne."],
	       2: ["Karta odwrócona – Kochliwość, obsesja,  zaślepienie, niezdecydowanie, niepewność, niewierność, rozczarowanie, zazdrość, zranienie, złudzenia.",
	           "Karta odwrócona – Strach przed uczuciowym zaangażowaniem, tęsknota, koniec miłości, toksyczny związek, kłótnie i nieporozumienia, nie liczenie się z potrzebami partnera, traumy wyniesione z poprzednich związków, podjęcie decyzji o rozwodzie, rozstaniu, zazdrość  przyczyną rozpadu związku, problemy z podejmowaniem decyzji, niepewność własnych racji, niezadowalający układ towarzyski, nielojalność przyjaciół, nieszczęśliwy w skutkach romans.",
	           "Zdrowie (karta odwrócona) – Wszelkie choroby dotyczące układu hormonalnego: przysadka, niedoczynność tarczycy, trzustka, nadnercza, choroby wywołane zaburzeniami hormonów płciowych. Karta może wskazywać na choroby związane z menopauzą i andropauzą oraz zespołem  napięcia przedmiesiączkowego."],}

chariot = {
	       0: ["Słowa kluczowe – podróż, energia w działaniu, wytrwałość, odwaga, dążenie do sukcesu, wpływ na przebieg wydarzeń , zwycięstwo, wiadomość, delegacja, transport naziemny, pojazd, poleganie na sobie, dobra passa.",
	           "Osoba – Człowiek dynamiczny i zrównoważony, osoba popularna, człowiek sukcesu, pracodawca, nawigator, pilot, kierowca, kierowca rajdowy, kochanek, pirat drogowy,tchórz, naciągacz, ktoś korzystający z tzw. układów.",
	           "Miejsce – Autostrada, droga, tor wyścigowy, garaż, salon samochodowy, warsztat mechaniczny, stadnina koni, dworzec.",], 
	       1: ["Cechy ogólne – Dynamizm, przedsiębiorczość, konsekwencja, ustalanie celów, determinacja, bystry umysł, otwarcie na różne możliwości, elastyczność, koncentracja na konkretnych celach, ambicja, przezwyciężenie konfliktu, poczucie własnej wartości, kontrola nad emocjami, rozsądek.",
	           "Znaczenie ogólne – karta Rydwanu ma proste przesłanie i mówi, że każdy z nas jest kowalem swojego losu i ponosi odpowiedzialność za własne życie. Nie wolno poddawać się biegowi zdarzeń, biernie stać odgrywając rolę ofiary będąc jedynie obserwatorem. Rydwan to bardzo pozytywna karta bo gwarantuje, że każdy ma w sobie potrzebne atuty, aby iść przez życie świadomie i odważnie, generując zdarzenia według własnego planu. Przy pomocy silnej motywacji, wiary i woli można osiągnąć co się zamierzyło. Nawet jeśli czasem na coś nie będziemy mieli wpływu, możemy wybrać samodzielnie jak poradzimy sobie z problemem. Karta symbolizuje czas szybkich zmian, nowe możliwości i postęp. To jest moment żeby pogodzić wszystkie atrybuty dojrzałej osobowości; bystry umysł, mądrość, rozsądek, energię, odwagę, emocje, uczucia i sprawne ciało i dokonać postępu w swoim życiu. W tym momencie wszystko zależy od nas. Przykładowe zdarzenia symbolizujące kartę: podróż po kraju, ważna podróż od której będzie zależała przyszłość, kupno samochodu, zmiana miejsca zamieszkania, przeprowadzka, ważna rozmowa, zaskakująca wiadomość, podejmowanie decyzji za kogoś kto sobie nie radzi, pomyślnie zdane egzaminy, awans w karierze zawodowej, odzyskanie pieniędzy od dłużnika, prestiż i sława, ogólnie dobra passa. W uczuciach przywrócenie zaniechanych relacji, pojawienie się partnera dla samotnej kobiety."],
	       2: ["Karta odwrócona – Niechęć do realizowania własnych marzeń i planów, lekkomyślność, skostnienie, brak elastyczności, tępy upór utrudniający postęp, bezwzględność w postępowaniu, niecierpliwość, egoizm, utrata kontroli nad sytuacją poczucia bezpieczeństwa, złość, agresja, mściwość, próżność, brak szacunku dla innych.",
	           "Karta odwrócona – Brawura przyczyną niebezpieczeństwa w podróży, złe emocje (gniew, złość), pracoholizm, wybuchowość, zbytnie eksploatowanie organizmu, mogą spowodować problemy z otoczeniem i zdrowotne. Karta w tym położeniu symbolizuje trudne sytuacje; opóźnienia w realizacji planów, złe wiadomości lub ich brak, odwołanie podróży, kłopoty z samochodem, niezdane egzaminy, załamanie kariery zawodowej, uniki, strach przed podjęciem decyzji, niepomyślny okres w życiu, w związkach nadmierna dominacja mężczyzny.",
	           "Zdrowie (karta odwrócona) – Problemy neurologiczne, choroba Parkinsona, stwardnienie rozsiane, niedowłady lub porażenia nerwów i kończyn, porażenie mózgowe, zaburzenia widzenia pochodzenia neurologicznego, amnezja, choroba lokomocyjna. Wszelkiego rodzaju nerwobóle np. rwa kulszowa, zespół nerwu barkowego, migrena."],}

justice = {
	       0: ["Słowa kluczowe – sprawiedliwość, uczciwość, prawo, przepisy prawne, wyrok, osąd, równowaga, szczerość,  fakty, racjonalizm, intelekt, statystyka, przyczyna i skutek.",
	           "Osoba – Sędzia, adwokat, radca prawny, rozjemca, księgowy, ktoś sprawiedliwy i zrównoważony, ktoś opierający się na faktach, przekupny urzędnik, niesprawiedliwy sędzia, ktoś naginający prawo.",
	           "Miejsce – Sala sądowa, notariat, sala egzaminacyjna, wszelkie instytucje i urzędy, które wiążą się z regulacją prawną.",], 
	       1: ["Cechy ogólne – Uczciwość, rozsądek, umiar, mądrość, bezstronność, obiektywizm, rozwaga, dobre intencje, zrozumienie innych poprzez analizę ich postępowania, moralność, porozumienie, racjonalny osąd oparty na faktach.",
	           "Znaczenie ogólne – Przesłaniem tej karty jest „odpowiadaj za siebie” i przypomnienie, że za wszystko w życiu trzeba kiedyś zapłacić. Dlatego przed podjęciem jakiejkolwiek decyzji należy rozważyć logicznie, obiektywnie, bez emocji, wszelkie aspekty sprawy. Działać sprawiedliwie, mądrze z wyczuciem, opierać się wyłącznie na faktach. Być może trzeba będzie przyznać się do winy? Kogoś przeprosić? Zadośćuczynić wyrządzoną niesprawiedliwość? Kiedy w kartach pojawia się Sprawiedliwość oznacza to, że w naszym życiu nadszedł czas na uporządkowanie w aspekcie społecznym i prawnym. Jesteśmy gotowi do trzeźwego osądu, bronienia swoich praw, kompromisów, dobrych wyborów, wybaczenia, zerwania ze złymi nawykami lub z przeszłością. Właśnie nadszedł dobry czas, sprawy (społeczne i sądowe)idą po naszej myśli bo działamy uczciwie i odpowiedzialnie. Inne aspekty tej karty to wszelkie kwestie prawne, podpisywanie kontraktów i umów, wypełnianie formularzy, składanie wszelkich dokumentów, sprawiedliwy przebieg spraw, szczerość w kontaktach, liczenie się z opinią innych, różne formy nowoczesnej edukacji, porady i konsultacje. W sprawach uczuć karta oznacza porozumienie i kompromis w istniejącym związku lub że przyjdzie to na co się zasłużyło. Cudowna miłość, nowy związek lub … odwrotnie"],
	       2: ["Karta odwrócona – Manipulacja, złe, niesprawiedliwe osądzanie, krytycyzm,  nieracjonalna ocena sytuacji, brak równowagi psychicznej, zaprzeczanie faktom, poczucie krzywdy, wyrzuty sumienia, nieumiejętność zaufania, postawa rezygnacji, fałszywe oskarżenie, źle ulokowane zaufanie, poniżenie.",
	           "Karta odwrócona – Karta symbolizuje wszelką nieprawość, popełnienie przestępstw i wykroczeń, niesprawiedliwe  traktowanie i osąd, dyskryminację, chęć wyrządzenia komuś krzywdy, odegrania się, postawa „oko za oko ząb za ząb”, wyrzuty sumienia, brak umiejętności wybaczania, trudności w załatwianiu wszelkich spraw urzędowych, biurokracja i łapówkarstwo, chaos i bałagan. W odniesieniu do osobowości symbolizuje kogoś o niskiej samoocenie, żyjącego w poczuciu winy, strachu przed złym fatum czy karą za grzechy. Po trudnych zdarzeniach nastąpiło zakłócenie równowagi psychicznej dobrze byłoby zwrócić się  o pomoc do specjalisty, pójście na terapię. W miłości i związkach to nierówność, dominacja jednej osoby nad drugą, podwójna gra, fałsz, zakończenie związku, rozwód.",
	           "Zdrowie (karta odwrócona) – Wszelkie schorzenia układu moczowego włącznie z niewydolnością nerek, choroba trzustki i śledziony."],}

hermit = {
	       0: ["Słowa kluczowe – poszukiwanie wewnętrznej mądrości, wartości ponadczasowe,  dyskrecja, odosobnienie, ostrożność, powaga, filantropia, przewodnictwo duchowe.",
	           "Osoba – Starzec, mędrzec, samotnik, człowiek o wysokim poziomie rozwoju duchowego, pracodawca, naukowiec, filozof, nauczyciel, lekarz, psycholog, emeryt, rencista, dziadek ,babcia, wdowiec, przewodnik, detektyw, nocny stróż, odludek, żebrak, kloszard.",
	           "Miejsce – Dowolne miejsce odosobnienia, zakon, biblioteka, pracownia naukowa, gabinet psychologa, więzienie, grota, miejsce na łonie natury, gdzie czujemy spokój i wyciszenie.",], 
	       1: ["Cechy ogólne – Cierpliwość, mądrość, religijność, dojrzewanie duchowe, samodzielność, samorealizacja, umiejętność słuchania, refleksja, abstrakcyjne myślenie, postawa humanitarna, kontemplacja, medytacja, troska, opiekuńczość, doświadczenie życiowe, dyskrecja, spokój wewnętrzny, wysoka samoocena, umiejętność uczenia się na cudzych błędach.",
	           "Znaczenie ogólne –Ogólnym przesłaniem karty Pustelnik jest boski wymiar w człowieku. To postawa życiowa aby preferować rozwój duchowy, pracować nad sobą, być wewnętrznie bogatym, „być” a nie tylko „mieć”. Osiągnąć spokój w podejściu do rzeczywistości. W codziennym życiu oznacza, że pora zastanowić się głębiej nad problemem o który spytaliśmy kart. Zamiast działać impulsywnie albo pod czyjąś presją lepiej wszystko przemyśleć, zanalizować. Trzeba zadać sobie parę podstawowych pytań np. dlaczego? po co? aby nie powtarzać wciąż tych samych błędów i nie krzywdzić siebie i innych. Należy poszukać (ukrytego sensu, osoby, rzeczy, prawdy). Inny aspekt karty to moment kiedy trzeba zastanowić się nad kolejnym etapem w życiu, zebrać motywację i siły. Może dobrze byłoby skończyć z wyścigiem szczurów i iść własną drogą? Albo zbytnia izolacja  od innych i życia  ogranicza nasz rozwój. Każda skrajna postawa jest niekorzystna. Możemy wybrać się w jakieś ustronne piękne miejsce i dać sobie trochę czasu na przemyślenia nad dalszym życiem lub konkretnymi planami. Jeśli sami nie potrafimy uporać się z problemem, dobrze byłoby poszukać na zewnątrz przewodnika. Starszego, bardziej doświadczonego i mądrego człowieka albo po prostu skorzystać z terapii u psychologa. Karta Pustelnika symbolizuje wszelkie terapie, pozbywanie się złych nawyków i nałogów, badania lekarskie, spokojny czas studiów i czytania interesujących książek np. o tematyce ezoterycznej, pracowitość, pomyślność w pracy i finansach, przejście na emeryturę, dobre zdrowie, kontakty z dziadkami. W miłości czas przemyśleń i refleksji. Konieczność szczerej rozmowy z partnerem."],
	       2: ["Karta odwrócona – Utrata wiary, samotność, lęk przed ludźmi i starością, ubóstwo duchowe i materialne, egoizm, oschłość, amnezja, uwiąd starczy, ograniczenia, pedanteria, uniki, błędna ocena faktów, odrzucenie możliwości rozwoju duchowego, kompleksy wynikające z niskiej samooceny, nieumiejętność wyciągania wniosków z przykrych doświadczeń.",
	           "Karta odwrócona – Karta sugeruje że unikamy zmierzenia się z problemami, które nadmiernie się skumulowały albo nie potrafimy zapomnieć o trudnej przeszłości. Ucieczka w marzenia, mocne wrażenia, czy ingerowanie w cudze życie(zajmowanie się sprawami osób z bliskiego i dalszego otoczenia) nic nie da. Jeśli nie poddamy się refleksji które zaowocują zmianami pozostaniemy samotni i nieszczęśliwi. Będziemy popełniać wciąż te same błędy !!! Inne znaczenia karty: trudna sytuacja życiowa spowodowana brakiem aktywności, wszelkie ograniczenia, negowanie ezoteryki i rozwoju duchowego, trudności we współżyciu z innymi ludźmi, wyobcowanie, skostnienie, obojętność, chłód emocjonalny, renta spowodowana złym stanem zdrowia.",
	           "Zdrowie (karta odwrócona) – Choroby przewlekłe, które można jedynie zaleczyć, złagodzić objawy. Mogą to być choroby alergiczne, gerontologiczne np. Alzhaimera, demencja, upośledzenie komórek i tkanek organizmu, starczy marazm, apatia, choroby płuc, oraz te które upośledzają narządy zmysłów wzrok, słuch i inne."],}

wheel = {
	       0: ["Słowa kluczowe – przeznaczenie, zmiana, hossa-bessa, nieuchronność, zbieg okoliczności, nieprzewidziane zdarzenia, przypadek.",
	           "Osoba – Ktoś, kogo los postawił na naszej drodze, osoba która potrafi pokonywać przeciwności losu, ktoś bardzo zajęty, osoba zmieniająca zdanie, ekspert w jakiejś dziedzinie, astrolog, ekonomista, biznesmen, finansista, zegarmistrz, mechanik, oszust finansowy, nieudacznik, ktoś kogo zły los postawił na naszej drodze.",
	           "Miejsce – Giełda, banki, kantory, sejfy, kasyno, karuzela, zakład napraw np. zegarmistrzowski, mechaniczny itp.",], 
	       1: ["Cechy ogólne – Nauka przystosowania, wiara w dobry los, ufność w dobrodziejstwo przeznaczenia, realizacja planów, koncentracja na wybranym celu, odwaga i determinacja do tworzenia czegoś nowego, zadowolenie, aktywność, twórcze natchnienie, wytrwałość, umiejętność wykorzystania życiowej szansy, mobilność, improwizacja.",
	           "Znaczenie ogólne – Kiedy pojawia się ta karta możemy mieć pewność że coś nowego wkracza w nasze życie. Będzie się działo… Jednak czy będzie to niespodziewane szczęście czy niepomyślne zdarzenie, zależy od nas. Jeśli odważnie podchodzimy do życia i realizujemy to co nam przyniesie,nie chowając głowy w piasek, dostaniemy grant od losu. Może to być jakaś druga szansa, niespodzianka która w cudowny sposób odmieni nasze życie albo wprawiliśmy w ruch pozytywną energię(podejmując odważne decyzje) i właśnie obecnie zadziałała nowym zdarzeniem. Teraz życie potoczy się w zawrotnym tempie a my musimy dostosować się do tego, zaufać przeznaczeniu, płynąć z nurtem, nie robić gwałtownych ruchów i nie obawiać się zmian. Na tej drodze czekają nas miłe zdarzenia i niespodzianki albo diametralna zmiana drogi życiowej. Koło Fortuny może oznaczać więc spełnienie i osiągnięcie wymarzonego celu we wszystkich aspektach życia oraz wszelkie wygrane losowe. W sprawach miłości oznacza nowy związek z przeznaczenia."],
	       2: ["Karta odwrócona – Niewykorzystanie nadarzającej się okazji, niedostrzeganie zmienności losu, przekonanie o prześladującym  fatum i braku wpływu na swój los, czarnowidztwo, ciągłe obawy, konflikty, podejrzliwość, marazm.",
	           "Karta odwrócona – W tej pozycji Koło Fortuny nie jest łaskawe, nie udało się ruszyć do przodu, lęki z przeszłości, frustracje, czy bujanie w obłokach zniweczyły dokonanie dobrych zmian w naszym życiu. Nastał nowy cykl, niczego sami nie zmieniliśmy więc ślepy los zrobi to za nas… niestety narobi tylko zła.. złe wydarzenia, kłopoty finansowe, kradzieże, nieudane decyzje, toksyczne nieudane związki, konflikty, straty, strach przed biedą, fatalne zbiegi okoliczności itp. zdarzenia. Karta w tej pozycji oznacza, że nie mamy żadnego wpływu na bieg wydarzeń, możemy ze spokojem czekać tylko na odmianę losu. Potem zrobić coś ze swoim życiem żeby kolejny raz nie doświadczyć przykrych niespodzianek.",
	           "Zdrowie (karta odwrócona) – wszystkie schorzenia wątroby, dróg żółciowych i trzustki, włącznie z nowotworem tych narządów. Karta oznacza także mechaniczne uszkodzenie śledziony."],}
	           
strength = {
	       0: ["Słowa kluczowe – siła ducha i ciała, odwaga, stanowczość, opanowanie, pasja, zwycięstwo, pewność siebie, zdrowie, witalność, namiętność.",
	           "Osoba – Silna, wzbudzająca pożądanie, namiętna i świadoma swoich walorów kobieta, osoba wykonująca niebezpieczną lub wymagającą siły pracę, artysta cyrkowy, sportowiec, kulturysta, ktoś kto dba o zdrowie i kondycję, despota, przestępca.",
	           "Miejsce – Miejsca związane ze sprawowaniem władzy, hala sportowa, siłownia, miejsca na łonie natury: pustynia, puszcza, plaża, góry, letnisko.",], 
	       1: ["Cechy ogólne – Wewnętrzna siła, niezwykły hart ducha, który pozwala pokonać trudne sytuacje, moc idąca ze środka, pozytywne nastawienie i myślenie, determinacja, duma, panowanie nad emocjami, cierpliwość, wytrwałość, samodyscyplina, odwaga, entuzjazm, pewność siebie, moralna władza. samorealizacja, stanowczość, aktywność, witalność, energia, pasja, wojowniczość, pożądanie, dojrzałość, zwycięstwo, ogromny potencjał.",
	           "Znaczenie ogólne – Symbolem przesłania tej karty może być powiedzenie „W zdrowym ciele zdrowy duch”, czyli moc ducha i ciała w jednym. Kiedy oba aspekty są ze sobą zharmonizowane człowiek tryska zdrowiem i energią, jest gotów do pokonania każdej przeszkody w życiu. Jego umysł i ciało stanowią tandem, któremu nic nie przeszkodzi bo ma wielki potencjał. W zdrowym ciele dobrze się czuje i działa zdrowy, sprawny, kreatywny umysł. Potęga łagodnej mądrości i dobroci może zwyciężyć siłę mocnych pięści i ciężkich słów. Znaczenie karty ma wiele aspektów; może się zdarzyć że przyjdzie nam zmierzyć się z czymś trudnym, nadszedł moment aby działać, bo wszystko w tej chwili zależy od nas, jest wielka szansa na powodzenie. Jednak często walka ta ma wymiar psychiczny i emocjonalny. Może się zdarzyć, że trzeba będzie komuś wybaczyć, współczuć, załagodzić sytuację, zapomnieć i zaakceptować odmienne potrzeby i racje innych. Wykazać się tolerancją i zrozumieniem. Z drugiej strony może właśnie przyszedł czas na zmierzenie się ze swoimi nałogami i walkę o dobre, zdrowe nawyki? Będąc konsekwentnym uprawiając sport, dbając o zdrową dietę i rozwój duchowy mamy szansę na krok w doskonaleniu siebie. Z kolei dysponując ogromną siłą ducha i potencjałem fizycznym, (mądrzy, zdrowi, atrakcyjni fizycznie) jesteśmy przykładem dla innych i możemy służyć im pomocą. Jeśli kogoś trapiła choroba teraz odzyska siły i pełnię zdrowia. W aspekcie miłosnym karta Mocy symbolizuje dojrzałe uczucia i wielką namiętność, spełnienie seksualne."],
	       2: ["Karta odwrócona – Przemoc fizyczna i psychiczna, agresja, nienawiść, wszelkie formy dominacji, głód władzy, działania destrukcyjne, zawziętość, zazdrość, depresja, podatność na zranienia i urazy, pesymizm, którego źródłem jest niewiara w siebie, tchórzostwo, lenistwo, wygodnictwo, brak taktu, krętactwa, gloryfikacja własnej osoby.",
	           "Karta odwrócona – Sytuacja nas przerosła, czujemy się bezbronni i sfrustrowani albo postępowanie innych doprowadziło nas do szału. Trudno opanować złość, zazdrość, agresję może nawet pragnienie zemsty. Wszystko o co trzeba zawalczyć, własne zdrowie, rozwój, dobry wygląd, wyzwania życiowe, przychodzi z wielkim trudem, braknie siły, cierpliwości i konsekwencji. Życie w ciągłym stresie nikomu nie służy więc jeśli nie zrobimy nic dla siebie skończy się to chorobą. Ciemną stroną mocy może być także niepohamowane korzystanie z życia, co doprowadzić może do manii wielkości i wszelkich uzależnień. Może nadeszła pora na udanie się do psychologa czy na terapię ?",
	           "Zdrowie (karta odwrócona) – Spadek energii życiowej organizmu uczucie zmęczenia, osłabienia, omdlenia, brak apetytu, brak snu lub nadmierna senność, obrzęki twarzy i kończyn, brak sił, zawroty głowy, anemia, powikłania poszczepienne. Układ odpornościowy organizmu; od częstych infekcji po choroby zakaźne."],}
	           
hangman = {
	       0: ["Słowa kluczowe – zawieszenie, zmiana punktu widzenia, refleksja, izolacja, oddalenie, stagnacja, bierność, uzależnienie, rezygnacja.",
	           "Osoba –Duchowny, muzyk ,chemik, mistyk, idealista, uczeń zapatrzony w swego mistrza, wierny przyjaciel, medium, nałogowiec – narkoman, alkoholik, więzień.",
	           "Miejsce – Zakon, filharmonia, sala koncertowa, szpital, internat, laboratoria chemiczne, miejsce wymuszonego wypoczynku, spotkania rodzinne i towarzyskie, te na których „musimy” się znaleźć bo wypada.",], 
	       1: ["Cechy ogólne – Dystans, poświęcenie, pokora, uduchowienie, telepatia, poczucie obowiązku, transformacja, rozwój duchowy i intelektualny, pobożność, dobry kontakt ze sobą, oderwanie od codzienności, przewartościowanie, nowe perspektywy, odmienne spojrzenie na świat i ludzi, dążenie do samopoznania, wycofanie się, kontemplacja, dyplomacja i takt, wewnętrzny spokój, refleksyjność, introwertyzm.",
	           "Znaczenie ogólne- Rutynowe myślenie i działanie mogło doprowadzić do sytuacji w której trzeba przystanąć, zawiesić chwilowo działania i przewartościować pewne aspekty naszego życia. Należałoby zadać sobie pytanie co jest Ważne a co Nie? Trudna sytuacja wymusiła na nas konieczność zmiany. Karta Wisielca kojarzy się z poniesieniem bolesnej straty, znalezieniem się na rozdrożu życia albo z sytuacją kiedy doszliśmy do granicy cierpliwości i wytrzymałości za którą jest już tylko możliwość transformacji. W codziennym życiu może to być np. utrata kogoś lub czegoś, choroba, uniezależnienie od grupy przyjaciół (bo być może nami manipulowali) rezygnacja z dotychczasowych priorytetów albo tzw. zawieszenie broni w związku czy wręcz chęć odejścia. Niezależnie co jest przyczyną trzeba będzie spojrzeć na życie z innej perspektywy. Dobrze więc byłoby nie robić niczego na siłę i popłynąć z prądem. Przystosować się do sytuacji, będąc otwartym i uważnym na nowe możliwości a przy okazji dojrzeć duchowo. Wisielec w kartach może też oznaczać mniej traumatyczne zdarzenia, sytuację w której po prostu nic się nie wydarzy, totalny zastój. To moment kiedy to my decydujemy się na taki rozwój sytuacji. Będzie to więc urlop na którym chcemy się odizolować, sytuacja w której nie zabieramy głosu aby nie zaburzać swoich układów w pracy czy rodzinie, przysięga milczenia czy sytuacja, która za jakiś czas ulegnie poprawie bez naszego udziału. Karta niekiedy może symbolizować kobietę ciężarną. W uczuciach trzeba będzie zapomnieć o przeszłości, wyciszyć emocje lub zastanowić się nad obecnym związkiem dokąd zmierza."],
	       2: ["Karta odwrócona – Pesymizm, brak energii, bierność, utrata spokoju, niechęć do jakiegokolwiek wysiłku intelektualnego, apatia, obłuda, ucieczka w nierealne światy,  nerwowość, chorobliwa zazdrość, drobiazgowość, formalizm , depresja, próżność, problemy w życiu codziennym, nieumiejętność radzenia sobie z przeciwnościami losu, strach przed odpowiedzialnością, problemy w kontaktach z innymi ludźmi, uzależnienia od używek.",
	           "Karta odwrócona – Wszystko stanęło na głowie i znikąd pomocy? Pustka, samotność i czegoś brak ?No cóż, to wynik tego, że w Twoim życiu zabrakło refleksji i chęci zmiany czegokolwiek. Odwrócona karta ma trudną symbolikę, która oznacza niemożność zachowania równowagi emocjonalnej, zasklepienie się w starych nawykach, wykręty, uciekanie od problemów itp. Rezultatem takiej postawy są przeszkody we wszelkich aspektach życia, wyczerpanie, przemęczenie. Przy słabej psychice może skończyć się apatią, depresją, chorobami, uzależnieniem od alkoholu, narkotyków czy nałogami związanymi z używaniem środków zmieniających świadomość. Mimo wszystko nie martw się zmiany nadejdą jeśli zrobisz ten pierwszy mały krok (może poprosisz o pomoc?)",
	           "Zdrowie (karta odwrócona) – Choroby psychiczne (autyzm, schizofrenia, manie i zespoły urojeniowe) oraz choroby powstałe na skutek uzależnienia od wszelkich używek (delirium tremens, psychozy, padaczka poalkoholowa, wycieńczenie organizmu)."],}
	           
death = {
	       0: ["Słowa kluczowe – koniec, rozstanie, strata, przełom, zamknięcie przeszłości, zmiana, bilans zysków i strat, odnowa, transformacja.",
	           "Osoba – Ktoś po ciężkich przeżyciach, rekonwalescent wdowa, wdowiec, chirurg, radiolog, pielęgniarka, weterynarz, grabarz, komornik, krytyk, osoba zmarła, ktoś śmiertelnie chory, osoba bezwzględna zadająca cierpienia.",
	           "Miejsce – Sanatoria, szpitale, hospicja, kostnica, zakład pogrzebowy, cmentarze, ruiny, opuszczony dom lub mieszkanie, nowe miejsce zamieszkania.",], 
	       1: ["Cechy ogólne – Akceptacja nieuchronności wydarzeń i zmian, konieczność dostosowania, umiejętność dojścia sedna sprawy, panowanie nad swoim życiem, odnowa, pozytywna transformacja, umiejętność odcinania się od starych problemów i spraw, przemiana wewnętrzna, dojrzewanie emocjonalne, zmiana światopoglądu, odpowiedzialność.",
	           "Znaczenie ogólne – Zapewne karta Śmierć budzi w Was niepokój, to zrozumiałe bo kojarzy się jednoznacznie. Jednak oprócz przykrych zdarzeń oznacza przede wszystkim totalną transformację. Coś się kończy ale jednocześnie coś nowego wkracza w nasze życie. Nie projektujmy sobie lęków a patrzmy z nadzieją, bo to co nadejdzie otworzy większe i  lepsze możliwości. Karta radzi aby odciąć definitywnie wszystko co już niepotrzebne i bolesne, co nie funkcjonuje prawidłowo albo w jakiś sposób nas ogranicza. W codziennym życiu może oznaczać odejście z relacji nas lub kogoś, rozwód, koniec przyjaźni, zmianę pracy, miejsca zamieszkania, środowiska, statusu. Symbolizuje nowy sposób życia i światopoglądu, porzucenie starych nawyków i przyzwyczajeń, polepszenie stanu zdrowia, diagnozę, wyzdrowienie fizyczne i emocjonalne, niezależność, wielkie porządki, generalny remont, ogromną zdolność do regeneracji sił. Czasami pojawienie się karty oznacza, że problem czy sprawa o którą pytamy nie jest wart naszego zaangażowania i nie odegra wielkiej roli w naszym życiu. Lepiej więc zająć się tym co naprawdę jest ważne. Tak istotne zmiany w życiu mogą napawać lękiem, kojarzyć się z bólem i cierpieniem, wszyscy to wiedzą ale min. z tego składa się nasze życie. Dlatego musimy nauczyć się innego podejścia do trudniejszych momentów. Trzeba sobie uświadomić podstawowe prawdy o życiu."],
	       2: ["Karta odwrócona – Obawy przed zmianami, nieumiejętność bycia odpowiedzialnym, strach przed chorobą, kalectwem i śmiercią, fatalizm, konserwatywny światopogląd, strach przed postępem, kurczowe trzymanie się przeszłości, pasywność, brak poczucia bezpieczeństwa, brak harmonii, znudzenie, stagnacja, myśli samobójcze.",
	           "Karta odwrócona – Symbolizuje żałobę, wydarzenia i sytuacje, które zakończą się w bolesny i nieoczekiwany sposób. Może być symbolem sytuacji bez wyjścia i niemożności realizacji naszych zamierzeń. Najlepiej w takim wypadku wycofać się gdyż prawdopodobnie jest to zły pomysł. Karta może oznaczać negatywną odpowiedź w jakiejś sprawie, w tym wypadku odpowiedź będzie definitywna bez możliwości odwołania. Karta powie o wszelkich zgubach, stratach czegoś, zerwaniu umowy, czy sprzedaży. Ostrzeże nas przed zwolnieniem z pracy, pogorszeniem stanu zdrowia i sytuacji materialnej, niespodziewanym zerwaniem związku czy odejściem kogoś bliskiego.",
	           "Zdrowie – karta nie mówi o konkretnej chorobie jest tylko jej symbolem w pozycji odwróconej."],}
	           
temperance = {
	       0: ["Słowa kluczowe – harmonia, równowaga, pojednanie, kompromis, komunikacja, dawanie i branie, wymiana.",
	           "Osoba – Osoba ugodowa, przyjaciel, miły kolega, sąsiad, opiekun, rozjemca, rodzice chrzestni, opiekun duchowy, stewardessa, pielęgniarka, lekarz, informatyk, tłumacz, dyplomata, elektryk, hydraulik, ktoś złośliwy i niezrównoważony, osoba konfliktowa.",
	           "Miejsce – Miejsce na łonie natury, potok, rzeka, droga, uzdrowisko, sąd pojednawczy, port, kolej, firma ,blok mieszkalny.",], 
	       1: ["Cechy ogólne – Łagodność, cierpliwość, zrównoważona osobowość, skromność, wstrzemięźliwość, dystans, obiektywizm, dokładność, wytrwałość, rzetelność, kreatywność, umiejętność znalezienia złotego środka, zaufanie, asertywność, zrozumienie, empatia, miłosierdzie, tolerancja, wrażliwość na innych.",
	           "Znaczenie ogólne – Niezwykle pozytywna karta Umiarkowanie jest symbolem etapu w życiu kiedy następuje czas odnalezienia równowagi, uleczenia duchowego i fizycznego. To moment kiedy udaje się osiągnąć harmonię w potrzebach ducha i ciała, co przynosi ukojenie i spokój. W życiu codziennym udaje się zdystansować do wielu spraw i przyjmować rzeczy takimi jakimi są. Kiedy Umiarkowanie pojawi się w rozkładzie można być pewnym, że wszystkie zmartwienia, kłopoty, niewyjaśnione czy bolesne sytuacje mają szansę zakończyć się pomyślnie. Można oczekiwać dobrych wiadomości, wyjaśnienia zawiłych spraw, rozmów, dyskusji pertraktacji zakończonych po naszej myśli. Umiar jest symbolem zgody, przebaczenia, pojednania, ceremonii chrztu, powrotu do zdrowia po ciężkiej chorobie, uleczeniem urazów emocjonalnych, nawiązaniem kontaktu z kimś na kim nam zależy, przyjaznych i ciepłych relacji, spotkań towarzyskich, dobrej współpracy w każdej dziedzinie życia. Może oznaczać akt seksualny lub wstrzemięźliwość. W miłości powolny rozwój uczuć. Ogólnie w czasie Umiaru umiemy pogodzić wszystkie aspekty życia; duchowość i materię, pracę i rozrywkę, potrzeby innych i własne. Rozwijamy zainteresowania i ze spokojem rozwiązujemy problemy. Karta radzi też aby w interesującej nas sprawie użyć dyplomacji lub pójść na kompromis. Delikatnie nakłania aby wyjść z inicjatywą a także zwrócić baczniejszą uwagę na potrzeby innych.W finansach kontrolować wydatki."],
	       2: ["Karta odwrócona –Nieuprzejmość, niedomówienia, popadanie w skrajności, brak równowagi, brak umiaru, złośliwość, nieumiejętność radzenia sobie z życiem, zbytnia wylewność, niecierpliwość, przewrażliwienie, zniechęcenie, utrata pewności siebie, poczucie niższości, osamotnienie, lęk przed okazywaniem uczuć, chłód emocjonalny, rozrzutność ,lenistwo, brak motywacji.",
	           "Karta odwrócona – Rozwiązywanie problemów na siłę czy przekonywanie innych do naszych koncepcji nie jest dobrym pomysłem bo nie przyniesie spodziewanych efektów. Brak równowagi emocjonalnej pozbawia siły i powoduje stres. To z kolei może skończyć się chorobą. W takim stanie niewiele można osiągnąć, ma się wrażenie że wszystko idzie jak po grudzie. W związkach uczucie dyskomfortu i poczucie niższości. Może rozmowa z kimś bliskim albo autorytetem mogłaby pomóc?",
	           "Zdrowie (karta odwrócona) – Zaburzenia równowagi wynikające z dysfunkcji błędnika. Problemy z kończynami dolnymi wszelkiego rodzaju, od prozaicznych nagniotków, ha luksów, zwichnięć, złamań, do dysplazji stawów biodrowych oraz żylaki i choroby zakrzepowe."],}
	           
devil = {
	       0: ["Słowa kluczowe – uzależnienie, materializm, wyrachowanie, pokusa, fałsz, zniewolenie, więzy, brak kontroli, żądze.",
	           "Osoba – Aktor, finansista, biznesmen, doradca, ktoś wpływowy, celebryta, osoba atrakcyjna seksualnie, narkoman, alkoholik, prostytutka, wróg, osoba nieszczera, przesadny moralista, uwodziciel/ka/,satanista, hazardzista, członek mafii, dewiant seksualny.",
	           "Miejsce – Bank, kasyno, agencja towarzyska, dom publiczny, nocny lokal, podejrzane spelunki, miejsca spotkań podejrzanych interesów i członków mafii",], 
	       1: ["Cechy ogólne – Umiejętność wywierania wpływu na innych, uzależnienie od kogoś lub czegoś, namiętność, głód władzy, rozwiązłość, troska o zaspokajanie potrzeb seksualnych partnera, wyrachowanie, materializm, manipulacja, obłuda, złe nawyki, nadmiernie wybujałe ego, niepohamowany temperament, otwartość na eksperymenty seksualne, pożądanie, brak jakichkolwiek zahamowań, perwersja, sukces dzięki nieuczciwości, przebłysk geniuszu, egocentryzm i egotyzm, hulaszczy tryb życia.",
	           "Znaczenia ogólne – Trudna karta symbolizująca wszelkie zło i pokusy na świecie. Tak naprawdę ten diabeł jest w każdym z nas. Problem w tym, że nie zawsze jesteśmy w stanie uświadomić sobie że mamy w sobie wielką siłę aby uwolnić się spod jego władzy. Bombardowani od dzieciństwa frazesami typu „nie dasz rady tego zrobić”, „jesteś jak ojciec czy matka”(w sensie negatywnym) ,,wszystkie kobiety są takie same,” ,,faceci to świnie,” ,,pieniądze nie dają szczęścia ale ułatwiają życie,” zarażani jesteśmy diabłem czyli stereotypowym myśleniem które zniewala, ogranicza i utrudnia wgląd we własne oceny. Stereotypy to początek diabelskiej mocy, kiedy im się poddamy wciągnie nas moc diabelskich ograniczeń. Pogoń za pieniądzem, czy tzw. używanie życia, trzymanie się kurczowo jakiejś sytuacji, osoby, czy poglądów, manipulowanie ludźmi dla własnych korzyści, traktowanie człowieka jak swoją własność czy seks jako lek na całe zło może skończyć się uzależnieniem, może wciągnąć nas świat z którego potem trudno się będzie wyplątać (np.wszelkie nałogi, trudny romans; trójkąt miłosny). Karta diabła sygnalizuje że możesz doświadczać wielu pokus w życiu, chęć doznawania przyjemności jest w każdym z nas, jednak kiedy zrobisz coś ponad zwykłą przyjemność popadniesz w nałóg z którego musisz wyzwolić się sam. Pilnuj więc aby przyjemności nie stały się sensem Twojego życia. Diabeł w kartach bywa czasem symbolem dużej wygranej."],
	       2: ["Karta odwrócona – Wykorzystywanie pozycji społecznej do złych celów, nadużywanie siły, skrajny materializm, uleganie wszelkim pokusom, głębokie uzależnienia od innych, nieumiejętność uwolnienia się spod wpływu jednego człowieka lub jakiejś grupy (sekty mafii, grupy przestępczej), głębokie dewiacje seksualne, urazy po molestowaniu seksualnym lub gwałcie, głębokie uzależnienia od wszelkich używek zmieniających świadomość, okrucieństwo, sadyzm, autodestrukcja, brak wiary w wyższe wartości, fanatyzm, tyrania, totalitaryzm, rasizm, wszelkiego rodzaju odchylenia i postawy ortodoksyjne.",
	           "Karta odwrócona – Symbolizuje to z czym nie potrafimy sobie poradzić,  uzależnieni i słabi nie panujemy nad własnym życiem. Wciągnął nas mroczny świat, z którego nie widzimy wyjścia albo ktoś z naszego otoczenia jest w takiej sytuacji. Pogrążeni w nałogach i depresji staczają się na samo dno. Karta w tej pozycji symbolizuje najtrudniejsze dla człowieka sytuacje, głębokie uzależnienia, toksyczne związki, upodlenie i wykorzystywanie innych, okrucieństwo, sadyzm, agresja, gwałt, praktyki seksualne odbiegające od normy, nadmierny popęd seksualny, czarna magia, przestępstwa, prostytucja, molestowanie nieletnich, brak skrupułów i wszelkich zasad moralnych.",
	           "Zdrowie (karta odwrócona) – Choroby zakaźne zagrażające życiu przenoszone drogą pokarmową lub przez krew min. AIDS. Wszelkiego rodzaju stany zapalne organizmu, charakteryzujące się  podwyższeniem ciepłoty ciała, choroby weneryczne, poważne dewiacje seksualne nekrofilia, gerontofilia, pedofilia, zoofilia."],}
	           
tower = {
	       0: ["Słowa kluczowe – wstrząs, zniszczenie, rozpad, kryzys, przegrana, nagła zmiana, olśnienie,  katharsis (oczyszczenie)",
	           "Osoba  – Geniusz, ktoś zdolny do wielkiego poświęcenia, saper,  pirotechnik, architekt, hutnik, strażak, murarz, osoba doznająca załamania po wielkim cierpieniu, złośnik, egoista, terrorysta, bandyta.",
	           "Miejsce – Oddział reanimacji, pasieka, plac budowy, biurowce, elektrownia, kotłownia, huta, ruiny, zgliszcza, miejsce przymusowego odosobnienia, góry, wysokie wzniesienie, wieża, dzwonnica.",], 
	       1: ["Cechy  ogólne  – Załamanie światopoglądu pod wpływem zdarzeń, nauka szybkiego przystosowania, nagłe oświecenie, determinacja w działaniach, budząca się siła, hart ducha w obliczu tragedii, pogodzenie z tym co nieuniknione, zmiana systemu wartości, zmiana osobowości, przewartościowywanie, uwolnienie ze skostniałych poglądów, wyzwolenie z więzów, przełamanie stereotypów w myśleniu i działaniu.",
	           "Znaczenie ogólne – Wieża to karta destrukcji, oznaczająca nagłe zdarzenie, które wstrząśnie dogłębnie  dotychczasowym życiem. Może to być zewnętrzna fizyczna zmiana rzeczywistości , wstrząs psychiczny spowodowany okolicznościami albo jedno i drugie. Może także oznaczać wyzwolenie się z ograniczających sytuacji , własnych chorych ambicji albo doznanie przebłysku wiedzy na jakiś temat. W życiu codziennym może to być zamach terrorystyczny, porwanie, wypadek komunikacyjny, nagłe zasłabnięcie, utrata pracy, pobicie, przemoc , włamanie, awantura, kłótnia, czyjaś złość lub pozytywnie odkrycie czegoś. W każdym razie będzie to  jakieś gwałtowne zdarzenie. Na niespodziewane wydarzenia losowe nie  mamy wpływu, jedynym wyjściem będzie zebranie w sobie siły duchowej do poradzenia sobie w tej sytuacji  lub poproszenie o wsparcie czy skorzystanie z psychoterapii. Inaczej rzecz się ma kiedy wieża jest symbolem naszego postępowania. Często budujemy ograniczające  schematy, gromadzimy stare uczucia, emocje, raniące wspomnienia, zamykamy się w naszym świecie iluzji i stęchlizny mentalnej zatruwając  siebie od środka. Albo wolimy nic nie robić marząc że samo się załatwi albo rozejdzie po kościach. Kiedy taki stan trwa zbyt długo może się zdarzyć , że  los ześle jakieś wydarzenie,  które potrząśnie psychiką aby wywołać zmiany i skierować życie na nowe tory. Takie doświadczenia bywają zbawienne dla nas ,choć mogą wywoływać bunt i lęk. Jednak bywają dobroczynne, ponieważ, pozwalają spojrzeć na życie z odmiennej, nowej perspektywy i dokonać zmian w życiu. Doznajemy przebłysku świadomości i zmieniamy swoje dotychczasowe  sztywne i skostniałe poglądy, nawyki albo relacje. Stare przysłowie mówi „Nie ma tego złego co by na dobre nie wyszło” i o to tu chodzi."],
	       2: ["Karta odwrócona – Zniechęcenie, niewola duchowa, zamęt, niemożność zaakceptowania zmian, nieumiejętność przystosowania, załamanie nerwowe, katastrofa, nieostrożność, szok, poczucie ograniczenia, wstrząs, załamanie osobowości, przygnębienie, nerwica, uraz, oszołomienie, bezsilność, długotrwały proces dochodzenia do równowagi.",
	           "Karta odwrócona – Karta w tej pozycji jest symbolem człowieka który nie potrafi pogodzić się z zaistniałym stanem rzeczy, nic nie zmienia, woli iluzję niż prawdę co doprowadzi go do jeszcze trudniejszych zdarzeń.  W życiu codziennym mogą to być bardzo drastyczne zmiany, ciężka choroba, bankructwo, utrata wolności, rozpad związku, wydarzenia niezwykle traumatyczne.",
	           "Zdrowie (karta odwrócona) – Schorzenia układu kostnego, reumatoidalne zapalenie stawów, osteoporoza, reumatyzm, dna moczanowa, łamliwość kości, gościec, gruźlica kości. Wszelkie schorzenia kręgosłupa: dyskopatia, skrzywienia kręgosłupa (skoliozy), rozszczepienie kręgosłupa, zapalenie rdzenia kręgowego, urazy kręgosłupa. Z odwróconą kartą Rycerza Pucharów oznacza nowotwory kości lub szpiku kostnego."],}
     	           
star = {
	       0: ["Słowa kluczowe – nadzieja,  miłość doskonała, harmonia, uzdrowienie, twórcza  inspiracja, piękno, optymizm, wiara, spełnianie marzeń, szczęście, przyjemność.",
	           "Osoba – Ktoś zakochany, piękny duchem a przez to i ciałem, szczęśliwy, uzdolniony artystycznie lub artysta, poeta, osoba atrakcyjna, przyjaciel, ogrodnik, ekolog, kosmetyczka, fałszywy przyjaciel, człowiek nie wykorzystujący swoich talentów.",
	           "Miejsce – Wyjątkowe i urokliwe miejsca ; ogrody, parki, malownicze krajobrazy, wystawy, galerie, piękne wnętrza, scena teatralna, operowa, miejsca przybytku kultury i sztuki, salon kosmetyczny, łazienka.",], 
	       1: ["Cechy ogólne – Ogromna wrażliwość  i intuicja, jasność i czystość intencji, optymizm, poczucie humoru, inspiracje, kreatywność, uzdolnienia, inwencja twórcza, natchnienie, oryginalność, inteligencja, niezależność, otwartość na nowe możliwości, wolność, pewność siebie, rozwój duchowy, wewnętrzna mądrość, przyjazny stosunek do ludzi.",
	           "Znaczenie ogólne – Cudowna, szczęśliwa karta uważana za ochronną, zapowiadająca szczęśliwy okres w życiu, tak jakby grant od losu. Często następuje po burzliwym okresie. Jest to czas wielkich nadziei optymizmu i wiary w dobrą przyszłość. Zdarzają się w życiu momenty magiczne, kiedy więc wyciągniesz kartę Gwiazdy, ten moment właśnie rozpoczynasz. Cokolwiek teraz zaczniesz będzie przynosiło radość i przyjemność. Twoje twórcze pomysły znajdą okazję do realizacji, będziesz cieszył się dobrym zdrowiem, witalnością, przypływem świeżych uczuć i doznań. Wiara i nadzieja zaprowadzą Cię dokąd zechcesz, tak w sferze duchowej jak i materialnej z wielką korzyścią dla Ciebie i innych. Twoja intuicja i kreatywność sprawią że możesz osiągnąć korzyści finansowe z tego co lubisz robić. Harmonia w duszy i wewnętrzna mądrość otworzą drogę do miłości i przyjaznych relacji z innymi ludźmi. Nawet jeśli w przeszłości nie było łatwo, to teraz jest moment na uzdrowienie sytuacji, przywrócenie równowagi i stabilizacji. Karta może oznaczać dobre inwestycje, dokształcanie, rozwijanie talentów, twórczy moment, rozwój duchowy, nowe pomysły, spędzanie czasu w przyjemny sposób, radość, optymizm. Czas powrotu do zdrowia, uleczenie duchowe i fizyczne. W uczuciach poprawienie stosunków w związkach, albo zupełnie nową  miłość , również platoniczną."],
	       2: ["Karta odwrócona – Nadwrażliwość, niepewność, brak wiary w siebie, zagubienie, brak intuicji, złudzenia, zamknięcie na nowe możliwości, brak pomysłów, brak inwencji, zmarnowany talent, rozmienianie się na drobne, ekscentryczność, pesymizm, zmęczenie, wydawanie błędnych opinii i sądów.",
	           "Karta odwrócona – Brak wiary w siebie i Opatrzność sprawia że niewiele zmienia się w Twoim życiu. Przeżywasz trudne chwile, być może podnosisz się po traumatycznych przeżyciach albo Twoje ambicje są tak wielkie że nie jesteś w stanie im sprostać. Trudno jest w tej chwili cokolwiek osiągnąć. Być może jesteś w trudnych relacjach niedoceniany przez bliską osobę. Poproś o duchowe wsparcie i miej nadzieję a sytuacja zmieni się na lepsze.",
	           "Zdrowie (karta odwrócona) – Wszystkie schorzenia płuc; rozedma, gruźlica, zapalenia, upośledzenie wentylacji płuc, choroby onkologiczne. Środkowa część układu oddechowego; oskrzela, oskrzeliki, astma, duszności, stany zapalne. Schorzenia kończyn górnych;  zastrzały, zanokcice, zwichnięcia, złamania, reumatyzm, artretyzm, porażenia niedowłady,  niezborność ruchowa."],}     
	           
moon = {
	       0: ["Słowa kluczowe – iluzje, złudzenia, wyobraźnia, intuicja, nierealność, zmienność, fałsz, tajemnica, trudny romans.",
	           "Osoba – Kobieta ciężarna, terapeutka, położna, ginekolog, opiekunka, osoba niezwykle oddana dla innych, twórca, restaurator, kucharz, ktoś kto żyje życiem innych ludzi, ktoś drażliwy na swoim punkcie,  macocha, kłamca, szantażysta.",
	           "Miejsce – Rodzinny dom, mieszkanie, dom pracy twórczej, jezioro, morze, bagno, rzeka, staw, pływalnia, restauracja, miejsca gdzie przebywają kobiety.",], 
	       1: ["Cechy ogólne – Podatność na wpływy, złudzenia, oszukiwanie samego siebie, wrażliwość, pełnia sił duchowych, inspiracja, kreatywność, intuicja, wyobraźnia, delikatność, romantyzm, fantazja, kompleksy, marzenia, wątpliwości, obiektywizm, zmienność.",
	           "Znaczenie ogólne – Magiczna karta symbolizująca niepowtarzalne, bogate wnętrze każdego człowieka oraz niejasne, tajemnicze sytuacje w nas albo na zewnątrz. Tak jak księżyc bywamy zmienni, ulegamy emocjom, uczuciom, nastrojom i iluzjom, marzymy, śnimy (miewamy nawet sny prorocze) albo podążamy za intuicją lub inspiracją realizując konkretne pomysły. Jest to pozytywna strona Księżyca i twórcze momenty w życiu, kiedy nastaje pora na wrażliwość, pobudzoną wyobraźnię, magię uczuć, inspirację, kreowanie siebie w twórczy sposób. W takiej chwili zmienia się nasze postrzeganie, punkt widzenia i dotychczasowe poglądy. Może się zdarzyć przełomowy moment w życiu (inicjacja seksualna, spotkanie wyjątkowej osoby, która odmieni nas albo przejście na emeryturę).Mniej pozytywny aspekt karty to tajemnice, iluzje i kłamstwa. Bywa że są to kłopotliwe i bolesne sprawy, które chcemy zataić przed światem albo bliscy, znajomi czy obcy ukrywają coś przed nami. Księżyc powoduje że jakieś sprawy widzimy w złym świetle, czegoś nie wiemy, albo idealizujemy. Karta symbolizuje wszelkie sytuacje podlegające zmianom np.; ktoś może zmienić zdanie, nie dotrzymać słowa, wycofać się, albo sprawa o którą pytamy wróci do punktu wyjściowego, może oznaczać zmianę pracy, adresu, planów czy partnera. Księżyc to rodzina i ciąża, kobiecy aspekt w naszym życiu, rozliczanie z przeszłością dotyczące matki lub innej kobiety, tajemny romans. To odczuwanie tęsknoty i kłopoty z przeszłością, marzenia o kimś lub o czymś nieosiągalnym, rozczarowanie, samotność, smutek, wątpliwości, pasywność, uległość, psychoterapia oparta na pracy z podświadomością."],
	       2: ["Karta odwrócona – Złośliwość, napastliwość, obgadywanie, zły humor, obsesje, niepewność, lęki, fobie, nadwrażliwość, depresja, zagubienie, niestałość, tęsknota, urazy, lenistwo, powolność, niezgrabność, niedotrzymywanie danego słowa, wycofanie, skłonność do nałogów.",
	           "Karta odwrócona – Karta w tym położeniu jest niebezpieczna, ponieważ ukazuje słabości, lęki, fobie i iluzje w których tkwi człowiek oraz odsłania to co chciałby zachować dla siebie; nieumiejętność radzenia sobie z samym sobą albo z ludzką perfidią. Przykłady takich sytuacji; cierpienie i tęsknota przekraczająca wszelkie granice, ucieczka od rzeczywistości, dręczące wyrzuty sumienia, choroba psychiczna, depresja, opętanie, obłęd, szaleństwo, uzależnienia od osób lub sytuacji, próby samobójcze, nałogi, samookaleczenia, destrukcyjne działania, toksyczne związki, rozstania.",
	           "Zdrowie – (karta odwrócona) Schorzenia żołądka; nieżyt, wrzody żołądka, nadprodukcja kwasu solnego, perforacja wrzodu żołądka, nowotwory, podrażnienia przewodu pokarmowego. Schorzenia przełyku; uchyłki przełyku, przepuklina rozworu przełykowego, polipy. Alergie pokarmowe i zatrucia typu salmonella, klebsiella, błędy dietetyczne i ich następstwa."],}

sun = {
	       0: ["Słowa kluczowe – witalność, dobro, optymizm, radość, sukces, szczęście, rozwój, kreatywność, spełnienie, czystość, miłość, prawda, autorytet, pozytywna energia, ciepło, potęga.",
	           "Osoba – Mężczyzna, osoba spełniona, pełna energii i witalności, lider, przywódca, artysta, pracownik naukowy, reżyser filmowy, ekspert w jakiejś dziedzinie, dyrektor, zgodne małżeństwo, mąż, ojciec, człowiek niespełniony i bierny, pełen obaw.",
	           "Miejsce – Miejsce wypoczynku na łonie przyrody, żyzne pola, plaże, ciepłe kraje, pustynia, stolice państw, urzędy, pomieszczenia w których przebywamy w dzień.",], 
	       1: ["Cechy ogólne – Człowiek optymistycznie nastawiony do życia, autorytet o silnej osobowości, wzbudzający sympatię i szacunek, pełen witalności i energii,  dojrzała osobowość o wysokim statusie społecznym, zadowolenie z realizacji planów, zaspakajanie ambicji, akceptacja życia i siebie, rozsądek, aktywność, spełnienie, świadomość, patriotyzm, zrozumienie, duma, uczciwość, pogoda ducha.",
	           "Znaczenie ogólne – Cudowna karta jak słoneczny, ciepły letni dzień jest symbolem przyjemności, radości i spełnienia. Archetyp Słońca to energia, przenikliwość, odwaga i umiejętność dostrzeżenia sedna sprawy. Daje nam pewność że na firmamencie naszego życia zdarzy się coś dobrego i namawia do realizowania wszystkich planów. O cokolwiek pytamy kart będzie miało wydźwięk pozytywny. Nawet kiedy obok Słońca znajdą się mniej przyjazne karty, ma ono właściwości osłabienia ich działania. Cokolwiek teraz się wydarzy będzie miało pozytywny rezultat. Życie płynie optymistycznym torem i przypomina letni dzień na plaży. Czujemy się młodzi, zdrowi, pełni energii, akceptujemy siebie i swoje możliwości, okazujemy innym dobroć i serdeczność. Słońce symbolizuje podróż, przeprowadzkę, słoneczne wakacje, dobrą zabawę, spełnienie  zawodowe, twórcze,  osiągnięcia akademickie, dyplomy, nagrody, rozpoczęcie nowego satysfakcjonującego związku przyjacielskiego lub miłosnego, w pełni akceptując bliskich bez oceniania kogokolwiek. W rodzinie pełnia szczęścia, oczekiwanie lub narodziny dziecka, świetny kontakt z dziećmi.Pamiętajcie, że szczęśliwa rodzina i udane dzieciństwo są bezcennym skarbem. Dobra atmosfera w domu,wzajemne zrozumienie i wsparcie zapewniają większe poczucie bezpieczeństwa niż największe pieniądze w banku:) a także dają zapas sił i zdrowie psychiczne na całe życie."],
	       2: ["Karta odwrócona – Egoizm, egocentryzm, narcyzm, próżność, robienie wszystkiego na pokaz, brak własnego zdania i pewności siebie, chęć przypodobania się, podatność na wpływy otoczenia, chorobliwe ambicje,  słomiany zapał, niestałość, znudzenie, apatia, narcyzm, nieszczerość w kontaktach, udawana życzliwość, arogancja, dominacja, zgorzkniałość.",
	           "Karta odwrócona – Odwrócone Słońce nie zapowiada wielkich problemów. Może się zdarzyć że pojawią się opóźnienia i przeszkody w planowanych sprawach. Nie jest to jednak coś poważnego, trzeba będzie wprowadzić jakieś niewielkie zmiany np. skorygować wygląd albo pójść na kurs  czy rozwinąć jakieś umiejętności. Problemem może być zbytnia pewność siebie i nie dostrzeganie potrzeb innych albo zbyt powierzchowne podejście do związków, co może doprowadzić do rozczarowań i niepowodzeń.",
	           "Zdrowie (karta odwrócona) – Choroby serca; choroba wieńcowa, zawał serca, wady zastawkowe, przerost mięśnia sercowego, zapalenia wsierdzia i osierdzia, patologie włókien mięśnia sercowego czyli kardiomiopatie. Choroby krwi; niedociśnienie i nadciśnienie, hemofilia, zbyt mała lub zbyt duża ilość czerwonych i białych krwinek oraz inne choroby wynikające z niedoboru czynników krzepnięcia."],}

judgement = {
	       0: ["Słowa kluczowe – osąd, rozliczanie, odrodzenie, wyzwolenie, wewnętrzna przemiana, poczucie ochrony Opatrzności, koniec i początek.",
	           "Osoba – Dziecko, noworodek, kuzyn, osoba spowinowacona, muzyk, speaker, dziennikarz, pracownik naukowy, ktoś  wierzący w swoje projekty i wcielający je w życie, fanatyk, osoba narzucająca własne przekonania i poglądy, konfliktowy krewny.",
	           "Miejsce – Sala sądowa, laboratorium, redakcja, sala koncertowa, rodzinny dom, miejsca do których tęsknimy, miejsca z przeszłości, ulice wielkich miast.",], 
	       1: ["Cechy ogólne – Przebudzenie do życia w zgodzie ze sobą i otoczeniem, osądzanie, rozliczanie, umiejętność dokonywania zmian, wyzwolenie, zdolności mediacyjne, ożywienie działalności, zdolność rozumienia innych, dobroć, empatia, dążenie do oświecenia, rozwój duchowy, wejście na wyższy poziom jaźni.",
	           "Znaczenie ogólne – Sąd Ostateczny jest symbolem przełomowego momentu w życiu, przebudzeniem, bilansem dotychczasowych dokonań, zysków i strat. Jest czasem głębokiej transformacji kiedy żegnamy się z przeszłością by wejść w nowy cykl. Mamy poczucie odrodzenia, oczyszczenia, pozbycia się dawnych ciążących sytuacji i rzeczywistości. Nadszedł nasz czas, mamy wrażenie że jesteśmy chronieni przez Opatrzność i nic nie jest w stanie przeszkodzić nowym wyzwaniom i działaniom. Odnowieni, odrzucamy poczucie winy i traumy przeszłości, wybaczamy sobie i innym, nie oceniamy nikogo zbyt surowo, staramy się tworzyć lepszą rzeczywistość mając dobry kontakt z otoczeniem. Karta namawia do konkretnego działania i wykorzystania nadarzających się okazji. To co w tej chwili zostanie zainicjowane, ma ogromne znaczenie bo skutki tych decyzji będą dalekosiężne. Karta mówi także o czymś co może się odrodzić na nowo, jakieś niewykorzystane talenty czy dawne relacje przyjacielskie lub miłosne. Sąd może oznaczać powrót do zdrowia, zakończenie trudnego związku, rozpoczęcie nowego, narodziny dziecka, bardzo dobre relacje w rodzinie, wyższy poziom edukacji lub podniesienie kwalifikacji, wybór nowej pracy, korzystną decyzję prawną, odkrycie naukowe, ważną wiadomość, która ma duży wpływ na bieg wydarzeń, dojrzała i mądra filozofia życiowa, mądra troska o rodzinę, kontakt z Bogiem."],
	       2: ["Karta odwrócona – Problemy wynikające ze złego osądu, lekceważenie innych, nierealne oczekiwania, lęk przed oceną, więzami i uczuciem, niezgodność charakterów, kreowania świata na siłę, brak naturalności w zachowaniach, fałszywe zdanie na swój temat, zamykanie się na nowości, skostnienie.",
	           "Karta odwrócona – Nowe plany i dalszy rozwój blokują lęki z przeszłości. Niepewność, niezdecydowanie i strach stanowią poważną przeszkodę. Inne znaczenia karty; poddanie się negatywnej ocenie innych, samooszukiwanie, nierealne oczekiwania powodem niemożności zrealizowania planów, poczucie winy, wyczekiwana wiadomość nie nadchodzi, skostnienie i trzymanie się starych zasad, niechęć do skorzystania z pomocy, kłopoty przez rodzinę, brak własnego mieszkania lub trudne warunki mieszkaniowe, toksyczne, karmiczne związki, niedostrzeganie nowych szans.",
	           "Zdrowie – (karta odwrócona) Choroby dolnego odcinka przewodu pokarmowego, włącznie z nowotworami tych organów; jelita cienkiego i grubego, okrężnicy, wyrostka robaczkowego, esicy, odbytnicy, odbytu."],}

world = {
	       0: ["Słowa kluczowe – spełnienie, sukces, zwycięstwo, dobrobyt, radość, szczęście, jedność, podróż, nagroda.",
	           "Osoba – Obcokrajowiec, laureat, szczęśliwy człowiek, ktoś o nieprzeciętnej wiedzy i intelekcie, opiekun, informatyk, architekt wnętrz, tancerz, haker komputerowy, silna osobowość nakłaniająca ludzi do zła.",
	           "Miejsce – Cały świat, konkretne miejsca na świecie i w ojczyźnie, miasto, dom rodzinny, kluby, placówki opiekuńcze, lotniska.",], 
	       1: ["Cechy ogólne – Tolerancja i szacunek dla innych, mądrość i wyrozumiałość, poczucie humoru, dobre samopoczucie, otwartość na wszelkie trendy i sytuacje, kreatywność, umiejętność wykorzystania wiedzy w dobrym celu, umiejętność czerpania wiedzy z wielu źródeł, błyskotliwość, myślenie potencjałami, zdolności językowe, panowanie nad sytuacją, realizacja wytyczonych celów, całkowite spełnienie.",
	           "Znaczenie ogólne – Ostatnia karta Wielkich Arkanów to koniec wędrówki po wyboistej drodze życia jaką przedstawił nam Tarot. Zamykamy pewien etap osiągnąwszy w obecnym cyklu sukces, spełnienie, szczęście  i zadowolenie. Spełnieni duchowo, fizycznie i materialnie, dojrzali i odpowiedzialni, będąc w harmonii ze sobą i otoczeniem, możemy w pełni napawać się stanem błogostanu zanim rozpoczniemy kolejny etap. Przyszedł czas na świętowanie, radość i zabawę. Swoją postawą zasłużyliśmy na wszystko co najlepsze, publiczny sukces, sławę, idealny związek, ciepło ogniska domowego, spełnienie zawodowe i osobiste. Świat leży u naszych stóp ￼  Karta Świat symbolizuje spokój i życie bez żadnych przykrych niespodzianek, korzystanie z efektów podjęcia dobrych decyzji, nowoczesność i technikę komputerową, osiągnięcie celu i sukces, przeprowadzkę, uzyskanie nagród i wyróżnień, spotkanie z ukochaną osobą której się dawno nie widziało, dobre kontakty z obcokrajowcami, dalekie podróże, odkrycie prawdy, które przyniesie spokój i ulgę, dochodowe zajęcie które wykonuje się z przyjemnością, pracę połączona z pasją, poczucie spełnienia i bezpieczeństwa, doskonałe zdrowie ."],
	       2: ["Karta odwrócona – Zamknięcie na świat i ludzi, samoograniczenie, niezdolność do samodzielnego myślenia, wąski punkt widzenia, problemy ze zdobywaniem wiedzy, koncentracją i logicznym myśleniem, ignorancja, ucieczka w wewnętrzny świat, brak cierpliwości do ludzi, niechęć pomagania i wspierania innych, brak tolerancji, ksenofobia.",
	           "Karta odwrócona – Przydałoby się trochę obiektywnej oceny samego siebie i celów do których zmierzasz, ponieważ widzisz tylko to co chcesz zobaczyć a iluzją długo się żyć nie da. Może się zdarzyć że żyjesz według planu i oczekiwań innych. Możliwe też że sukces dla Ciebie stał się pułapką, wyzwalając lęk czy zdołasz go powtórzyć. Nie poddaj się temu uczuciu bo pozbawi Cię aktywności i ulegniesz stagnacji. Inne znaczenia karty; życie wyłącznie dla miłości i miłością, kłopoty z obcokrajowcami, niemożność osiągnięcia wyznaczonych celów, lekkomyślność, sukces po czasie, który już nie cieszy, zniechęcenie, apatia, strach czy sobie poradzisz, zamknięcie w swoim świecie, zaniedbywanie życia duchowego, niechęć do nowoczesności, materialistyczne podejście do życia.",
	           "Zdrowie – (karta odwrócona) Wszelkie choroby psychiki; nerwica, depresja, fobie (irracjonalne lęki, klaustrofobia itp.)oraz kompulsje czyli uzależnienia nie zmieniające stanu świadomości (palenie, nałogowe zakupy)."],}

new = {
	       0: ["neutral",
	           "neutral1",
	           "neutral2",], 
	       1: ["good	       ",
	           "good2"],
	       2: ["bad",
	           "bad2",
	           "bad3"],}
	           
# ÏA! ÏA! Nyarlathothep!
# Tik-Tak człowiek!
